/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as publicScheduleRouteImport } from './routes/(public)/schedule'
import { Route as publicCoursesIndexRouteImport } from './routes/(public)/courses/index'
import { Route as publicCoursesIdRouteImport } from './routes/(public)/courses/$id'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicScheduleRoute = publicScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicCoursesIndexRoute = publicCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicCoursesIdRoute = publicCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/schedule': typeof publicScheduleRoute
  '/courses/$id': typeof publicCoursesIdRoute
  '/courses/': typeof publicCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/schedule': typeof publicScheduleRoute
  '/courses/$id': typeof publicCoursesIdRoute
  '/courses': typeof publicCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/schedule': typeof publicScheduleRoute
  '/(public)/courses/$id': typeof publicCoursesIdRoute
  '/(public)/courses/': typeof publicCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/schedule' | '/courses/$id' | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/schedule' | '/courses/$id' | '/courses'
  id:
    | '__root__'
    | '/'
    | '/(public)'
    | '/(public)/schedule'
    | '/(public)/courses/$id'
    | '/(public)/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/schedule': {
      id: '/(public)/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof publicScheduleRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/courses/': {
      id: '/(public)/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof publicCoursesIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/courses/$id': {
      id: '/(public)/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof publicCoursesIdRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicScheduleRoute: typeof publicScheduleRoute
  publicCoursesIdRoute: typeof publicCoursesIdRoute
  publicCoursesIndexRoute: typeof publicCoursesIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicScheduleRoute: publicScheduleRoute,
  publicCoursesIdRoute: publicCoursesIdRoute,
  publicCoursesIndexRoute: publicCoursesIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
