/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as publicSelectedRouteImport } from './routes/(public)/selected'
import { Route as publicCoursesRouteImport } from './routes/(public)/courses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSelectedRoute = publicSelectedRouteImport.update({
  id: '/(public)/selected',
  path: '/selected',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCoursesRoute = publicCoursesRouteImport.update({
  id: '/(public)/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof publicCoursesRoute
  '/selected': typeof publicSelectedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof publicCoursesRoute
  '/selected': typeof publicSelectedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(public)/courses': typeof publicCoursesRoute
  '/(public)/selected': typeof publicSelectedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/courses' | '/selected'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/courses' | '/selected'
  id: '__root__' | '/' | '/(public)/courses' | '/(public)/selected'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  publicCoursesRoute: typeof publicCoursesRoute
  publicSelectedRoute: typeof publicSelectedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/selected': {
      id: '/(public)/selected'
      path: '/selected'
      fullPath: '/selected'
      preLoaderRoute: typeof publicSelectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/courses': {
      id: '/(public)/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof publicCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  publicCoursesRoute: publicCoursesRoute,
  publicSelectedRoute: publicSelectedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
